search_dirs = [
  "$HOME",
  "/mnt/storage/Downloads",
  "/mnt/storage/Software/Customization"
]

fd_flags = [
  "--ignore-vcs",
  "--type", "file",
  "--type", "directory",
  "--hidden",
  "--follow"
]

ignored_dirs = [
  "$HOME/.cache",
  "$HOME/.config",
  "/mnt/storage/Downloads/Video/Captures/New folder",
  "/mnt/storage/Downloads/Documents/WindowsPowerShell",
  "/mnt/storage/Software/Customization/TrafficMonitor"
]

