search_dirs = [
  "$HOME",
  "/mnt/HDD/Downloads",
  "/mnt/HDD/Software/Customization",
  "/mnt/HDD/Music"
]

fd_flags = [
  "--ignore-vcs",
  "--type", "file",
  "--type", "directory",
  "--hidden",
  "--follow"
]

ignored_dirs = [
  "$HOME/.cache",
  "$HOME/.config",
  "/mnt/HDD/Downloads/Video/Captures/New folder",
  "/mnt/HDD/Downloads/Documents/WindowsPowerShell",
  "/mnt/HDD/Software/Customization/TrafficMonitor"
]

